[package]
name = "crossfire"
version = "0.1.5"
authors = ["plan <frostyplanet@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/qingstor/crossfire-rs"
readme = "README.md"
repository = "https://github.com/qingstor/crossfire-rs"
documentation = "https://docs.rs/crossfire"
keywords = ["async", "non-blocking", "lock-free", "channel"]
categories = ["concurrency", "data-structures"]
exclude = ["/ci/*", "/bors.toml"]
description = "channels for async and threads"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7"
async-trait = "0.1"
futures = "0.3"

[dev-dependencies]
log = { version = "0.4"}
stderrlog = "0.4.1"
tokio = { version = "0.2", features = ["time", "sync", "rt-threaded"] }
rand = "0.7.3"
