name: pr-validation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build with default
      run: cargo build --verbose

    - name: Build with tokio
      run: cargo build -F tokio --verbose

    - name: Build with async_std
      run: cargo build -F async_std --verbose

    - name: Run tests with tokio
      run: make test

    - name: Run tests with tokio
      run: make test_async_std timeout
